### ISSUE TITLE
Fix Campground Instance 

### ISSUE THREAD

**Issue by mgrosen** [cs373gc-fall-2016/SWEetOutdoors#67]
- [x] Duplicate Instances in database/table
- [x] Showing HTML as a string in campground description
- [x] Description Block is the only block showing up
- [x] All campgrounds have default picture.

**Comment by mgrosen** [comment]
HTML is for description and directions is now rendering correctly.

**Comment by ejjhaynes** [comment]
removed picture entirely, added state park and state blocks
